
name: Main Deployment

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: "cd /home/www/www.ping.fm/www/data-recovery-software && git config core.filemode false
 &&  git pull origin main && cd /home/www/www.ping.fm/www/ && chown -R ping.fm:ping.fm data-recovery-software && cd /home/www/www.ping.fm/www/howto && git config core.filemode false
 &&  git pull origin main && cd /home/www/www.ping.fm/www/ && chown -R ping.fm:ping.fm howto"
